# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-08 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=255)),
                ('hex_color', models.CharField(max_length=6)),
            ],
        ),
    ]
