# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_folder_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentdata',
            name='folder',
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.Folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='documents.Folder'),
        ),
    ]
