# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_create_root_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foldercustompermission',
            name='for_instance',
        ),
        migrations.AddField(
            model_name='foldercustompermission',
            name='for_instance',
            field=models.ManyToManyField(to='documents.Folder'),
        ),
    ]
