# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20170628_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foldercustompermission',
            old_name='for_instance',
            new_name='for_instances',
        ),
    ]
