# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20170604_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentdata',
            name='status',
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.Status'),
        ),
    ]
