# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20170604_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentdata',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(help_text='this is help text', max_length=60, verbose_name='name'),
        ),
    ]
