# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 15:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permissions', '0003_auto_20170620_2149'),
        ('documents', '0005_auto_20170702_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCustomPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_instances', models.ManyToManyField(to='documents.Document')),
                ('groups', models.ManyToManyField(blank=True, to='permissions.Group')),
                ('permissions', models.ManyToManyField(to='permissions.Permission')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
