# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-03 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_documenteditmeta_remark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remark',
            old_name='from_user',
            new_name='user',
        ),
        migrations.AddField(
            model_name='document',
            name='current_edit_meta',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.DocumentEditMeta'),
        ),
        migrations.AddField(
            model_name='remark',
            name='status',
            field=models.CharField(choices=[('0', 'Active'), ('1', 'Accepted'), ('2', 'Rejected')], default='0', max_length=1),
        ),
    ]
