# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-04 13:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0011_auto_20170804_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='followers',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
