# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-05 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_remark_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remark',
            name='detail',
        ),
    ]
