# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-06 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_auto_20170806_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='accepted_edit_meta',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_edit_meta', to='documents.DocumentEditMeta'),
        ),
    ]
