# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-06 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_documenteditmeta_previous_document_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documenteditmeta',
            old_name='accepted_by',
            new_name='closed_by',
        ),
    ]
