# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-06 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_auto_20170806_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenteditmeta',
            name='status',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='remark',
            name='status',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
