# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-15 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_remove_documenteditmeta_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentdata',
            name='name',
        ),
    ]
