# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-15 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_remove_documentdata_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='No name', max_length=255),
        ),
    ]
