# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-20 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    FolderCustomPermission = apps.get_model("documents", "FolderCustomPermission")
    DocumentCustomPermission = apps.get_model("documents", "DocumentCustomPermission")

    FolderCustomPermission.objects.all().delete()
    DocumentCustomPermission.objects.all().delete()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('documents', '0022_document_name'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
        migrations.RemoveField(
            model_name='documentcustompermission',
            name='for_instances',
        ),
        migrations.RemoveField(
            model_name='foldercustompermission',
            name='for_instances',
        ),
        migrations.AddField(
            model_name='documentcustompermission',
            name='for_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Document'),
        ),
        migrations.AddField(
            model_name='foldercustompermission',
            name='for_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Folder'),
        ),
    ]
