# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-26 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0023_custom_permissions_for_instances_m2m_to_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('0', 'Open'), ('1', 'In progress'), ('2', 'Project'), ('3', 'Final'), ('4', 'Close')], default='0', max_length=2),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
