# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-26 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0024_auto_20170826_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('0', 'Open'), ('2', 'Project'), ('3', 'Final'), ('4', 'Close')], default='0', max_length=2),
        ),
    ]
