# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-26 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0025_auto_20170826_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='archived',
        ),
    ]
