# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-03 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0026_remove_document_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('0', 'Open'), ('2', 'Project'), ('3', 'Final'), ('4', 'Close')], default='0', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='documentdata',
            name='file',
            field=models.FileField(upload_to='documents/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
