# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-13 04:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='0', max_length=1)),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='issueitem',
            name='status',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='remark',
            name='issue_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.IssueItem'),
        ),
        migrations.AddField(
            model_name='remark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues_remark_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
