# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-03 15:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0002_auto_20180313_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueitem',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
