# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-08 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('issues', '0003_issueitem_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='labels.Label'),
        ),
    ]
