# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-08 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('issues', '0004_issue_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='label',
        ),
        migrations.AddField(
            model_name='issue',
            name='labels',
            field=models.ManyToManyField(to='labels.Label'),
        ),
    ]
