# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-15 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_auto_20180409_1916'),
        ('issues', '0005_auto_20180408_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='labels',
        ),
        migrations.AddField(
            model_name='issueitem',
            name='labels',
            field=models.ManyToManyField(to='labels.Label'),
        ),
    ]
