# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-19 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_auto_20180415_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueitem',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
    ]
