# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('inherit', models.ManyToManyField(to='permissions.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=60)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='permissions.Permission')),
            ],
            options={
                'default_related_name': 'translations',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='permissions',
            field=models.ManyToManyField(to='permissions.Permission'),
        ),
    ]
