# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_insert_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='code',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
