---
env_name: "demo"
project_namespace: "ripa_archive"

nginx_host: "localhost"
nginx_port: "12340"
nginx_server_name: "13.75.126.239"
nginx_listen_port: 80
nginx_server_full_name: "{{ nginx_server_name }}"
nginx_scheme: "http"
gunicorn_workers: 2

project_linux_user: "www-data"
project_linux_group: "www-data"

project_dir: "/var/www/demo"
project_virtualenv_dir: "{{ project_dir }}/venv"
project_static_media_dir: "{{ project_dir }}/static_media"
project_work_tree: "{{ project_dir }}/work_tree"

git_repo: "git@bitbucket.org:sys_int64/ripa_archive.git"
git_version: "master"
git_ssh_key: "/var/www/.ssh/id_rsa"

# Django
allowed_host: "*"
DJANGO_SETTINGS_MODULE: "{{ project_namespace }}.settings.demo"
luna_vision_faces_list: "user_faces_staging"
celery_vhost: "/"

# Solr
solr_archive_url: "http://apache-mirror.rbc.ru/pub/apache/lucene/solr/6.6.0/solr-6.6.0.zip"

solr_version: "6.6.0"
solr_linux_user: "www-data"
solr_linux_group: "www-data"
solr_port: "8983"
solr_core: "{{ project_namespace }}"
solr_endpoint: "{{ nginx_scheme }}://{{ nginx_server_name }}:{{ solr_port }}"
