# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-02 12:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0009_documenteditmeta_remark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('target_id', models.PositiveIntegerField(null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField()),
                ('document_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.DocumentData')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
