# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-06 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_documenteditmeta_previous_document_data'),
        ('activity', '0002_auto_20170802_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='document_edit_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.DocumentEditMeta'),
        ),
    ]
