ACTIVITY_CREATE_DOCUMENT = "Created document \"{name}\" (path: Root/{path})"
ACTIVITY_CREATE_FOLDER = "Created folder \"{name}\" (path: Root/{path})"
ACTIVITY_RENAME_DOCUMENT = "Rename document from \"{old_name}\" to \"{new_name}\""
ACTIVITY_RENAME_FOLDER = "Rename folder from \"{old_name}\" to \"{new_name}\""
ACTIVITY_MOVE_DOCUMENT = "Move document from \"Root/{old_path}\" to \"Root/{new_path}\""
ACTIVITY_MOVE_FOLDER = "Move folder from \"Root/{old_path}\" to \"Root/{new_path}\""
ACTIVITY_REVERT_DOCUMENT = "Revert document from {datetime}"

NOTIFICATION_REMARK_ACCEPTED = "Was accepted remark"
NOTIFICATION_REMARK_FINISHED = "Remark was marked as \"finished\""
NOTIFICATION_REMARK_REJECTED = "Was rejected remark"
NOTIFICATION_REMARK_WROTE = "Was wrote remark"
NOTIFICATION_DOCUMENT_ACCEPTED = "Was accepted new version of document"
NOTIFICATION_DOCUMENT_REJECTED = "Was rejected new version of document"
