# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-27 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='position'),
        ),
        migrations.AddField(
            model_name='user',
            name='web_site',
            field=models.URLField(blank=True, max_length=100, verbose_name='web_site'),
        ),
    ]
