---
- apt_repository:
    repo: "ppa:jonathonf/python-3.6"

- name: install packages
  when: ansible_os_family == "Debian"
  apt: pkg={{ item.name }} state=present
  with_items:
  - name: nginx-full
  - name: python-pip
  - name: python3.6
  - name: python3.6-dev
  - name: python3.6-venv
  - name: virtualenv
  - name: runit
  - name: git
  - name: gettext
  - name: rabbitmq-server
  - name: python-psycopg2
  - name: postgresql-9.5
  - name: postgresql-server-dev-9.5
  - name: postgresql-client-9.5

