---
#- name: create solr directory
#  file: path=/opt/solr owner={{ solr_linux_user }} group={{ solr_linux_group }} state=directory
#
#- name: download and unarchive solr
#  unarchive: src={{ solr_archive_url }} dest=/opt/solr remote_src=True
#  become_user: "{{ solr_linux_user }}"
#
#- name: create runit solr directory
#  file: path=/etc/sv/{{ env_name }}_solr state=directory
#
#- name: copy runit solr config
#  template: src=runit_solr.j2 dest=/etc/sv/{{ env_name }}_solr/run mode=0755
#  notify:
#    - restart solr
#
#- name: create symlink runit solr config
#  file: src=/etc/sv/{{ env_name }}_solr dest=/etc/service/{{ env_name }}_solr state=link

# Solr config core
- name: create solr core directory
  file:
    path: "/opt/solr/solr-{{ solr_version }}/server/solr/{{ solr_core }}"
    owner: "{{ solr_linux_user }}"
    group: "{{ solr_linux_group }}"
    state: "directory"

- name: check current list of solr cores.
  uri:
    url: "{{ solr_endpoint }}/admin/cores"
    return_content: yes
  register: solr_cores_current

