# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-05 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20170805_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='detail',
            field=models.TextField(blank=True),
        ),
    ]
