# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-03 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('language_code', models.CharField(max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='notification',
            name='text',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
        migrations.AddField(
            model_name='notificationtranslation',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.Notification'),
        ),
    ]
