---
- name: restart nginx
  service: name=nginx state=restarted enabled=yes

- name: restart gunicorn
  runit: name={{ env_name }}_gunicorn state=restarted

- name: restart solr
  runit: name={{ env_name }}_solr state=restarted
